### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by AdmiralRazorbeard** [bibviz/bibviz#6]
I'd like to help by doing a french translation but it seems that other translations were not merged and the spanish translation option isn't available in langSelect

**Comment by Brayan-Jaimes** [comment]
> I'd like to help by doing a french translation but it seems that other translations were not merged and the spanish translation option isn't available in langSelect

Yeah, it seems to be the case

**Comment by danielgtaylor** [comment]
It is no longer dead. We've moved to a GitHub organization and anybody who wants to get involved can.
